### PR TITLE
feat: support gzip sitemaps

### PR DESCRIPTION
**Pull request by jasonaibrahim**
Hi @seantomburke 

Great library. I'd like to add support for sitemaps that use gzip compression.

This PR adds support for gzip sitemaps by using zlibs `gzip` method on urls that match a `.gz` extension

Please let me know if there is anything you'd like me to change or add.

### CODE REVIEW

**Comment by seantomburke** [comment]
Awesome! And thanks for adding the test. I'll take a look and get this merged and released as soon as I can.

**Comment by jasonaibrahim** [comment]
FYI - my IDE automatically removed some spaces based on `.editorconfig` settings. Let me know if you'd like me to revert those changes.

**Comment by seantomburke** [comment]
@jasonaibrahim Test looks good, everything else looks good! I'll add comments to the method and do some clean up once merged.

**Comment by seantomburke** [comment]
@jasonaibrahim Changes have been released to npm: sitemapper@3.1.12

**Pull request merged**
